FROM python:3.11-slim

WORKDIR /app

# Copy the entire python-api directory into /app/python-api
COPY python-api ./python-api

# Change directory
WORKDIR /app/python-api

# Install requirements
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Start command
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
