name: delta-whatsapp
services:
  - name: whatsapp-service
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
    ports:
      - port: 3001
        protocol: http
    env:
      - key: PORT
        value: "3001"
      - key: NODE_ENV
        value: production
    regions:
      - was
    instance_type: nano
    volumes:
      - name: whatsapp-sessions
        mount_path: /app/sessions
        size: 1
