FROM python:3.11-slim

WORKDIR /app

# We are running from inside python-api, so COPY . copies the python-api folder contents
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port
EXPOSE 8000

# Start command
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
